### ISSUE TITLE
免驱网卡速率显示问题

### ISSUE THREAD

**Issue by ff19** [Bluestar-coder/Hases-z7-kp7sc-10.15.4-OC#11]
大佬，问一下，你的那张94360cs2连wifi最大速率显示是多少，我这不知道为什么只有刚开始的时候显示最高866bps，后来就只有234mbps或者434，虽然测速是超过234的

**Comment by Bluestar-coder** [comment]
WiFi速度的显示 一般跟路由有关吧。 只要实际速度达到其实这个显示多少都无所谓的

**Comment by ff19** [comment]
我估计买了张有问题的94360cs2，windows下修改设备属性大概率卡死，win和macos都只能跑400mbps左右,有时开机也会卡住，只能彻底断电才能开机，就退了。后来换了张94352z,不卡机了,window下iperf3能跑600mpbs+了，macos下iperf3只有390mps左右，爬github看到老外推荐1820a可以2x2跑满866

**Comment by ff19** [comment]
换成闲鱼上A1466拆机的bcm94360cs2完美了，淘宝某些商家的卡有问题
