### ISSUE TITLE
z7m kp7sc与z7 kp7sc

### ISSUE THREAD

**Issue by jianjianXM** [Bluestar-coder/Hases-z7-kp7sc-10.15.4-OC#3]
z7m kp7sc与z7 kp7sc是不是只是缩水了显卡

**Comment by Bluestar-coder** [comment]
好像是的

**Comment by jianjianXM** [comment]
> 好像是的

那我改天试试

**Comment by jianjianXM** [comment]
> > 好像是的
> 
> 那我改天试试

现在笔记本有其他问题 等我修好试试

**Comment by Bluestar-coder** [comment]
> > > 好像是的
> > 
> > 
> > 那我改天试试
> 
> 现在笔记本有其他问题 等我修好试试

好的   最近我会进行调试big sure的系统 期待吧

**Comment by jianjianXM** [comment]
> > > > 好像是的
> > > 
> > > 
> > > 那我改天试试
> > 
> > 
> > 现在笔记本有其他问题 等我修好试试
> 
> 好的 最近我会进行调试big sure的系统 期待吧

好的

**Comment by Bluestar-coder** [comment]
> > > > > 好像是的
> > > > 
> > > > 
> > > > 那我改天试试
> > > 
> > > 
> > > 现在笔记本有其他问题 等我修好试试
> > 
> > 
> > 好的 最近我会进行调试big sure的系统 期待吧
> 
> 好的

Big Sur 已经OK

**Comment by jianjianXM** [comment]
> > > > > > 好像是的
> > > > > 
> > > > > 
> > > > > 那我改天试试
> > > > 
> > > > 
> > > > 现在笔记本有其他问题 等我修好试试
> > > 
> > > 
> > > 好的 最近我会进行调试big sure的系统 期待吧
> > 
> > 
> > 好的
> 
> Big Sur 已经OK

大佬牛逼 周末试试

**Comment by wy164519317** [comment]
感谢大佬，这两天正在搞碰到的问题不少，晚上试试大佬的efi
