### ISSUE TITLE
能吃bigsur了吗？是不是需要更新驱动

### ISSUE THREAD

**Issue by kiraraty** [Bluestar-coder/Hases-z7-kp7sc-10.15.4-OC#6]

**Comment by kiraraty** [comment]
安装bigsur成功了  http://bbs.pcbeta.com/viewthread-1879510-1-1.html
相似模具

**Comment by Bluestar-coder** [comment]
BigSur 已经可以了

**Comment by chehongwei-git** [comment]
@Bluestar-coder  请问可以系统内升级吗？

**Comment by kiraraty** [comment]
可以



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hongwei ***@***.***&gt;; 
发送时间: 2021年3月23日(星期二) 晚上11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Bluestar-coder/Hases-z7-kp7sc-10.15.4-OC] 能吃bigsur了吗？是不是需要更新驱动 (#6)





 
@Bluestar-coder  请问可以系统内升级吗？
